import turtle
window = turtle.Screen()
window.bgcolor("purple")
a = turtle.Turtle()
#a.color("purple")
#a.setposition(-200,-200)
a.shape("turtle")
a.color("black")
a.pensize(5) # turtle pen size
a.right(90)
a.backward(300)
a.left(90)
a.forward(150)
a.right(90)
a.forward(150)
a.right(90)
a.forward(150)
a.left(135)
a.forward(200)
window.exitonclick()
